/*
================================================================================
01_createStagingTable.sql
================================================================================
Creates stg.encounters_raw — the transient, text-only landing zone.

Design principles:
  - All 93 source columns stored as NVARCHAR(500) — no type coercion.
  - No CHECK constraints, no foreign keys — maximum permissiveness.
  - Truncated at the start of each new load batch.
  - _load_batch_id is NVARCHAR(20) to hold the YYYYMMDD_HHMMSS
    timestamp string generated by the Python loader.

================================================================================
*/
USE HCWarehouse_N2;
GO

CREATE TABLE stg.encounters_raw (
    -- System columns (not in source CSV)
    _stg_id             BIGINT          NOT NULL
                            CONSTRAINT pk_stg_encounters PRIMARY KEY IDENTITY,
    _load_batch_id      NVARCHAR(20)    NOT NULL,   -- e.g. '20260622_143201'
    _loaded_at          DATETIME2(0)    NOT NULL
                            CONSTRAINT df_stg_loaded_at DEFAULT SYSUTCDATETIME(),

    -- All 93 source columns stored as plain text (no interpretation)
    patient_id              NVARCHAR(500)   NULL,
    birth_year              NVARCHAR(500)   NULL,
    age                     NVARCHAR(500)   NULL,
    sex                     NVARCHAR(500)   NULL,
    race_ethnicity          NVARCHAR(500)   NULL,
    state                   NVARCHAR(500)   NULL,
    encounter_id            NVARCHAR(500)   NULL,
    icd10_code              NVARCHAR(500)   NULL,
    diagnosis_display       NVARCHAR(500)   NULL,
    diagnosis_category      NVARCHAR(500)   NULL,
    severity_index          NVARCHAR(500)   NULL,
    comorbidity_count       NVARCHAR(500)   NULL,
    has_diabetes            NVARCHAR(500)   NULL,
    has_hypertension        NVARCHAR(500)   NULL,
    has_chf                 NVARCHAR(500)   NULL,
    sbp_mmhg                NVARCHAR(500)   NULL,
    dbp_mmhg                NVARCHAR(500)   NULL,
    heart_rate_bpm          NVARCHAR(500)   NULL,
    spo2_pct                NVARCHAR(500)   NULL,
    temperature_f           NVARCHAR(500)   NULL,
    bmi                     NVARCHAR(500)   NULL,
    respiratory_rate        NVARCHAR(500)   NULL,
    hba1c_pct               NVARCHAR(500)   NULL,
    glucose_mg_dl           NVARCHAR(500)   NULL,
    creatinine_mg_dl        NVARCHAR(500)   NULL,
    wbc_10e3_ul             NVARCHAR(500)   NULL,
    nt_probnp_pg_ml         NVARCHAR(500)   NULL,
    medication_adherence_pdc NVARCHAR(500)  NULL,
    readmission_30d_flag    NVARCHAR(500)   NULL,
    triage_timestamp        NVARCHAR(500)   NULL,
    admit_timestamp         NVARCHAR(500)   NULL,
    bed_request_time        NVARCHAR(500)   NULL,
    bed_assign_time         NVARCHAR(500)   NULL,
    unit_assigned           NVARCHAR(500)   NULL,
    bed_occupancy_pct       NVARCHAR(500)   NULL,
    cpt_code                NVARCHAR(500)   NULL,
    procedure_display       NVARCHAR(500)   NULL,
    or_start                NVARCHAR(500)   NULL,
    or_end                  NVARCHAR(500)   NULL,
    actual_or_minutes       NVARCHAR(500)   NULL,
    or_turnover_minutes     NVARCHAR(500)   NULL,
    los_days                NVARCHAR(500)   NULL,
    discharge_timestamp     NVARCHAR(500)   NULL,
    safety_incident_flag    NVARCHAR(500)   NULL,
    incident_type           NVARCHAR(500)   NULL,
    incident_severity       NVARCHAR(500)   NULL,
    claim_id                NVARCHAR(500)   NULL,
    payer                   NVARCHAR(500)   NULL,
    npi_billing             NVARCHAR(500)   NULL,
    drg_weight              NVARCHAR(500)   NULL,
    submitted_charge_usd    NVARCHAR(500)   NULL,
    allowed_amount_usd      NVARCHAR(500)   NULL,
    patient_responsibility_usd NVARCHAR(500) NULL,
    fraud_upcoding_flag     NVARCHAR(500)   NULL,
    fraud_duplicate_flag    NVARCHAR(500)   NULL,
    fraud_unbundling_flag   NVARCHAR(500)   NULL,
    nurse_emp_id            NVARCHAR(500)   NULL,
    nurse_role              NVARCHAR(500)   NULL,
    nurse_unit              NVARCHAR(500)   NULL,
    nurse_tenure_years      NVARCHAR(500)   NULL,
    nurse_fte               NVARCHAR(500)   NULL,
    surgeon_emp_id          NVARCHAR(500)   NULL,
    surgeon_specialty       NVARCHAR(500)   NULL,
    shift_hours             NVARCHAR(500)   NULL,
    patients_per_nurse_ratio NVARCHAR(500)  NULL,
    overtime_hours          NVARCHAR(500)   NULL,
    burnout_exhaustion_mbi  NVARCHAR(500)   NULL,
    burnout_cynicism_mbi    NVARCHAR(500)   NULL,
    burnout_personal_accomplishment_mbi  NVARCHAR(500)  NULL,
    turnover_risk_index     NVARCHAR(500)   NULL,
    cahps_nurse_communication NVARCHAR(500) NULL,
    cahps_doctor_communication NVARCHAR(500) NULL,
    cahps_responsiveness    NVARCHAR(500)   NULL,
    cahps_pain_management   NVARCHAR(500)   NULL,
    cahps_discharge_info    NVARCHAR(500)   NULL,
    cahps_care_transition   NVARCHAR(500)   NULL,
    cahps_cleanliness       NVARCHAR(500)   NULL,
    cahps_quietness         NVARCHAR(500)   NULL,
    surgical_kit_id         NVARCHAR(500)   NULL,
    kit_name                NVARCHAR(500)   NULL,
    kit_unit_cost_usd       NVARCHAR(500)   NULL,
    kit_current_stock       NVARCHAR(500)   NULL,
    kit_reorder_point       NVARCHAR(500)   NULL,
    kit_lead_time_days      NVARCHAR(500)   NULL,
    kit_expiration_date     NVARCHAR(500)   NULL,
    stockout_risk_flag      NVARCHAR(500)   NULL,
    weekly_procedure_volume NVARCHAR(500)   NULL,
    projected_demand_4wk    NVARCHAR(500)   NULL,
    days_of_supply          NVARCHAR(500)   NULL,
    hedis_hba1c_tested      NVARCHAR(500)   NULL,
    hedis_hba1c_poor_control NVARCHAR(500)  NULL,
    pdsa_cycle_id           NVARCHAR(500)   NULL,
    himss_emram_stage       NVARCHAR(500)   NULL
);
GO
