/*
================================================================================
03_usp_loadFromStaging.sql
================================================================================
bronze.usp_loadFromStaging
--------------------------
Reads all rows from stg.encounters_raw, casts every column to its correct
SQL Server type using TRY_CAST / TRY_CONVERT, and inserts only the rows
that pass all casts and CHECK constraints into bronze.encounters.

Rows that fail a cast or constraint are silently skipped — the count is
returned via @rows_rejected so the Python caller can print it to the console.

Note: UNIQUEIDENTIFIER changed to NVARCHAR(20) for @batch_id to match
the timestamp-based batch_id generated by the simplified Python loader.

================================================================================
*/
USE HCWarehouse_N2;
GO

CREATE OR ALTER PROCEDURE bronze.usp_loadFromStaging
-- Variables for feeding the user back with the loading numbers and stats
    @batch_id       NVARCHAR(20),   -- e.g. '20260622_143201'
    @rows_loaded    INT             = 0 OUTPUT,
    @rows_rejected  INT             = 0 OUTPUT,
    @rows_flagged   INT             = 0 OUTPUT,  -- unused here; kept for interface parity
    @duration_ms    INT             = 0 OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @start_time DATETIME2 = SYSUTCDATETIME();

    -- This is for protecting the bronze layer from duplication
    IF EXISTS (
        SELECT 1 FROM bronze.encounters WHERE _load_batch_id = @batch_id
    )
    BEGIN
        PRINT '  [SKIP] Batch ' + @batch_id
              + ' already present in bronze.encounters — no rows inserted.';
        PRINT '         To reprocess: EXEC dbo.usp_deleteBatch '''
              + @batch_id + ''';';
        SET @rows_loaded  = 0;
        SET @rows_rejected = 0;
        SET @duration_ms  = DATEDIFF(MILLISECOND, @start_time, SYSUTCDATETIME());
        RETURN;
    END;

    -- TRUNCATE TABLE bronze.encounters;

    -- ── Step 1: Cast all 93 source columns to their Bronze types ─────────────
    -- TRY_CAST / TRY_CONVERT return NULL (instead of raising an error) when
    -- a value cannot be converted. This lets us identify bad rows below.
    WITH casted AS (
        SELECT
            _load_batch_id,
            -- Demographics
            patient_id,
            TRY_CAST(birth_year             AS SMALLINT)        AS birth_year,
            TRY_CAST(age                    AS SMALLINT)        AS age,
            sex,
            race_ethnicity,
            state,
            -- Clinical
            encounter_id,
            icd10_code,
            diagnosis_display,
            diagnosis_category,
            TRY_CAST(severity_index         AS DECIMAL(10,4))   AS severity_index,
            TRY_CAST(comorbidity_count      AS TINYINT)         AS comorbidity_count,
            TRY_CAST(has_diabetes           AS TINYINT)         AS has_diabetes,
            TRY_CAST(has_hypertension       AS TINYINT)         AS has_hypertension,
            TRY_CAST(has_chf                AS TINYINT)         AS has_chf,
            TRY_CAST(sbp_mmhg               AS DECIMAL(8,2))    AS sbp_mmhg,
            TRY_CAST(dbp_mmhg               AS DECIMAL(8,2))    AS dbp_mmhg,
            TRY_CAST(heart_rate_bpm         AS DECIMAL(8,2))    AS heart_rate_bpm,
            TRY_CAST(spo2_pct               AS DECIMAL(8,2))    AS spo2_pct,
            TRY_CAST(temperature_f          AS DECIMAL(8,2))    AS temperature_f,
            TRY_CAST(bmi                    AS DECIMAL(8,2))    AS bmi,
            TRY_CAST(respiratory_rate       AS SMALLINT)        AS respiratory_rate,
            TRY_CAST(hba1c_pct              AS DECIMAL(8,2))    AS hba1c_pct,
            TRY_CAST(glucose_mg_dl          AS DECIMAL(8,2))    AS glucose_mg_dl,
            TRY_CAST(creatinine_mg_dl       AS DECIMAL(8,2))    AS creatinine_mg_dl,
            TRY_CAST(wbc_10e3_ul            AS DECIMAL(8,2))    AS wbc_10e3_ul,
            TRY_CAST(nt_probnp_pg_ml        AS DECIMAL(10,2))   AS nt_probnp_pg_ml,
            TRY_CAST(medication_adherence_pdc AS DECIMAL(10,4)) AS medication_adherence_pdc,
            TRY_CAST(readmission_30d_flag   AS TINYINT)         AS readmission_30d_flag,
            -- Operational (style 126 = ISO 8601 format from the CSV)
            TRY_CONVERT(DATETIME2(0), triage_timestamp,    126) AS triage_timestamp,
            TRY_CONVERT(DATETIME2(0), admit_timestamp,     126) AS admit_timestamp,
            TRY_CONVERT(DATETIME2(0), bed_request_time,    126) AS bed_request_time,
            TRY_CONVERT(DATETIME2(0), bed_assign_time,     126) AS bed_assign_time,
            unit_assigned,
            TRY_CAST(bed_occupancy_pct      AS DECIMAL(8,2))    AS bed_occupancy_pct,
            TRY_CAST(cpt_code               AS INT)             AS cpt_code,
            procedure_display,
            TRY_CONVERT(DATETIME2(0), or_start,            126) AS or_start,
            TRY_CONVERT(DATETIME2(0), or_end,              126) AS or_end,
            TRY_CAST(actual_or_minutes      AS INT)             AS actual_or_minutes,
            TRY_CAST(or_turnover_minutes    AS SMALLINT)        AS or_turnover_minutes,
            TRY_CAST(los_days               AS INT)             AS los_days,
            TRY_CONVERT(DATETIME2(0), discharge_timestamp, 126) AS discharge_timestamp,
            TRY_CAST(safety_incident_flag   AS TINYINT)         AS safety_incident_flag,
            incident_type,
            incident_severity,
            -- Financial
            claim_id,
            payer,
            TRY_CAST(npi_billing            AS BIGINT)          AS npi_billing,
            TRY_CAST(drg_weight             AS DECIMAL(10,4))   AS drg_weight,
            TRY_CAST(submitted_charge_usd   AS DECIMAL(12,2))   AS submitted_charge_usd,
            TRY_CAST(allowed_amount_usd     AS DECIMAL(12,2))   AS allowed_amount_usd,
            TRY_CAST(patient_responsibility_usd AS DECIMAL(12,2)) AS patient_responsibility_usd,
            TRY_CAST(fraud_upcoding_flag    AS TINYINT)         AS fraud_upcoding_flag,
            TRY_CAST(fraud_duplicate_flag   AS TINYINT)         AS fraud_duplicate_flag,
            TRY_CAST(fraud_unbundling_flag  AS TINYINT)         AS fraud_unbundling_flag,
            -- HR
            nurse_emp_id,
            nurse_role,
            nurse_unit,
            TRY_CAST(nurse_tenure_years     AS DECIMAL(10,4))   AS nurse_tenure_years,
            TRY_CAST(nurse_fte              AS DECIMAL(10,4))   AS nurse_fte,
            surgeon_emp_id,
            surgeon_specialty,
            TRY_CAST(shift_hours            AS TINYINT)         AS shift_hours,
            TRY_CAST(patients_per_nurse_ratio AS TINYINT)       AS patients_per_nurse_ratio,
            TRY_CAST(overtime_hours         AS DECIMAL(8,2))    AS overtime_hours,
            TRY_CAST(burnout_exhaustion_mbi AS DECIMAL(10,4))   AS burnout_exhaustion_mbi,
            TRY_CAST(burnout_cynicism_mbi   AS DECIMAL(10,4))   AS burnout_cynicism_mbi,
            TRY_CAST(burnout_personal_accomplishment_mbi AS DECIMAL(10,4)) AS burnout_personal_accomplishment_mbi,  -- ++ ADDED: MBI third subscale
            TRY_CAST(turnover_risk_index    AS DECIMAL(10,4))   AS turnover_risk_index,
            TRY_CAST(cahps_nurse_communication   AS DECIMAL(8,2)) AS cahps_nurse_communication,
            TRY_CAST(cahps_doctor_communication  AS DECIMAL(8,2)) AS cahps_doctor_communication,
            TRY_CAST(cahps_responsiveness        AS DECIMAL(8,2)) AS cahps_responsiveness,
            TRY_CAST(cahps_pain_management       AS DECIMAL(8,2)) AS cahps_pain_management,
            TRY_CAST(cahps_discharge_info        AS DECIMAL(8,2)) AS cahps_discharge_info,
            TRY_CAST(cahps_care_transition       AS DECIMAL(8,2)) AS cahps_care_transition,
            TRY_CAST(cahps_cleanliness           AS DECIMAL(8,2)) AS cahps_cleanliness,
            TRY_CAST(cahps_quietness             AS DECIMAL(8,2)) AS cahps_quietness,
            -- Supply Chain
            surgical_kit_id,
            kit_name,
            TRY_CAST(kit_unit_cost_usd      AS DECIMAL(12,2))   AS kit_unit_cost_usd,
            TRY_CAST(kit_current_stock      AS SMALLINT)        AS kit_current_stock,
            TRY_CAST(kit_reorder_point      AS SMALLINT)        AS kit_reorder_point,
            TRY_CAST(kit_lead_time_days     AS SMALLINT)        AS kit_lead_time_days,
            TRY_CONVERT(DATE, kit_expiration_date, 126)         AS kit_expiration_date,
            TRY_CAST(stockout_risk_flag     AS TINYINT)         AS stockout_risk_flag,
            TRY_CAST(weekly_procedure_volume AS SMALLINT)       AS weekly_procedure_volume,
            TRY_CAST(projected_demand_4wk   AS SMALLINT)        AS projected_demand_4wk,
            TRY_CAST(days_of_supply         AS DECIMAL(10,4))   AS days_of_supply,
            -- Quality
            TRY_CAST(hedis_hba1c_tested     AS TINYINT)         AS hedis_hba1c_tested,
            TRY_CAST(hedis_hba1c_poor_control AS TINYINT)       AS hedis_hba1c_poor_control,
            pdsa_cycle_id,
            TRY_CAST(himss_emram_stage      AS TINYINT)         AS himss_emram_stage
        FROM stg.encounters_raw
        WHERE _load_batch_id = @batch_id
    ),

    -- ── Step 2: Identify rows with any cast failure or range violation ────────
    -- A failed TRY_CAST on a NOT NULL column produces NULL — detected here.
    -- The CASE returns NULL for clean rows (no issue found).
    rejects AS (
        SELECT *,
            CASE
                -- Cast failures on NOT NULL columns
                WHEN birth_year               IS NULL THEN 'birth_year'
                WHEN age                      IS NULL THEN 'age'
                WHEN severity_index           IS NULL THEN 'severity_index'
                WHEN spo2_pct                 IS NULL THEN 'spo2_pct'
                WHEN has_diabetes             IS NULL THEN 'has_diabetes'
                WHEN has_hypertension         IS NULL THEN 'has_hypertension'
                WHEN has_chf                  IS NULL THEN 'has_chf'
                WHEN medication_adherence_pdc IS NULL THEN 'medication_adherence_pdc'
                WHEN readmission_30d_flag     IS NULL THEN 'readmission_30d_flag'
                WHEN triage_timestamp         IS NULL THEN 'triage_timestamp'
                WHEN admit_timestamp          IS NULL THEN 'admit_timestamp'
                WHEN or_start                 IS NULL THEN 'or_start'
                WHEN or_end                   IS NULL THEN 'or_end'
                WHEN discharge_timestamp      IS NULL THEN 'discharge_timestamp'
                WHEN safety_incident_flag     IS NULL THEN 'safety_incident_flag'
                WHEN npi_billing              IS NULL THEN 'npi_billing'
                WHEN drg_weight               IS NULL THEN 'drg_weight'
                WHEN submitted_charge_usd     IS NULL THEN 'submitted_charge_usd'
                WHEN allowed_amount_usd       IS NULL THEN 'allowed_amount_usd'
                WHEN fraud_upcoding_flag      IS NULL THEN 'fraud_upcoding_flag'
                WHEN nurse_fte                IS NULL THEN 'nurse_fte'
                WHEN shift_hours              IS NULL THEN 'shift_hours'
                WHEN patients_per_nurse_ratio IS NULL THEN 'patients_per_nurse_ratio'
                WHEN burnout_exhaustion_mbi   IS NULL THEN 'burnout_exhaustion_mbi'
                WHEN burnout_personal_accomplishment_mbi IS NULL THEN 'burnout_personal_accomplishment_mbi'  -- ++ ADDED
                WHEN turnover_risk_index      IS NULL THEN 'turnover_risk_index'
                WHEN himss_emram_stage        IS NULL THEN 'himss_emram_stage'
                -- CHECK constraint range violations
                WHEN severity_index           NOT BETWEEN 0.0 AND 1.0  THEN 'severity_index_range'
                WHEN spo2_pct                 NOT BETWEEN 70 AND 100   THEN 'spo2_pct_range'
                WHEN medication_adherence_pdc NOT BETWEEN 0 AND 1      THEN 'pdc_range'
                WHEN nurse_fte                NOT BETWEEN 0 AND 1      THEN 'nurse_fte_range'
                WHEN shift_hours              NOT IN (8, 10, 12)       THEN 'shift_hours_value'
                WHEN patients_per_nurse_ratio NOT BETWEEN 1 AND 12     THEN 'nurse_ratio_range'
                WHEN burnout_exhaustion_mbi   NOT BETWEEN 0 AND 6      THEN 'exhaustion_range'
                WHEN burnout_cynicism_mbi     NOT BETWEEN 0 AND 6      THEN 'cynicism_range'
                WHEN burnout_personal_accomplishment_mbi NOT BETWEEN 0 AND 6 THEN 'pa_mbi_range'  -- ++ ADDED
                WHEN turnover_risk_index      NOT BETWEEN 0 AND 1      THEN 'turnover_risk_range'
                WHEN himss_emram_stage        NOT BETWEEN 0 AND 7      THEN 'himss_stage_range'
                ELSE NULL   -- NULL = clean row
            END AS failed_col
        FROM casted
    )

    -- ── Step 3: Insert only clean rows into Bronze ────────────────────────────
    -- WHERE failed_col IS NULL keeps only the rows that passed all checks.
    INSERT INTO bronze.encounters (
        _load_batch_id, patient_id, birth_year, age, sex, race_ethnicity, state,
        encounter_id, icd10_code, diagnosis_display, diagnosis_category,
        severity_index, comorbidity_count, has_diabetes, has_hypertension, has_chf,
        sbp_mmhg, dbp_mmhg, heart_rate_bpm, spo2_pct, temperature_f, bmi,
        respiratory_rate, hba1c_pct, glucose_mg_dl, creatinine_mg_dl,
        wbc_10e3_ul, nt_probnp_pg_ml, medication_adherence_pdc, readmission_30d_flag,
        triage_timestamp, admit_timestamp, bed_request_time, bed_assign_time,
        unit_assigned, bed_occupancy_pct, cpt_code, procedure_display,
        or_start, or_end, actual_or_minutes, or_turnover_minutes,
        los_days, discharge_timestamp, safety_incident_flag, incident_type, incident_severity,
        claim_id, payer, npi_billing, drg_weight,
        submitted_charge_usd, allowed_amount_usd, patient_responsibility_usd,
        fraud_upcoding_flag, fraud_duplicate_flag, fraud_unbundling_flag,
        nurse_emp_id, nurse_role, nurse_unit, nurse_tenure_years, nurse_fte,
        surgeon_emp_id, surgeon_specialty, shift_hours, patients_per_nurse_ratio,
        overtime_hours, burnout_exhaustion_mbi, burnout_cynicism_mbi,
        burnout_personal_accomplishment_mbi,  -- ++ ADDED: MBI third subscale
        turnover_risk_index,
        cahps_nurse_communication, cahps_doctor_communication, cahps_responsiveness,
        cahps_pain_management, cahps_discharge_info, cahps_care_transition,
        cahps_cleanliness, cahps_quietness,
        surgical_kit_id, kit_name, kit_unit_cost_usd, kit_current_stock,
        kit_reorder_point, kit_lead_time_days, kit_expiration_date, stockout_risk_flag,
        weekly_procedure_volume, projected_demand_4wk, days_of_supply,
        hedis_hba1c_tested, hedis_hba1c_poor_control, pdsa_cycle_id, himss_emram_stage
    )
    SELECT
        @batch_id, patient_id, birth_year, age, sex, race_ethnicity, state,
        encounter_id, icd10_code, diagnosis_display, diagnosis_category,
        severity_index, comorbidity_count, has_diabetes, has_hypertension, has_chf,
        sbp_mmhg, dbp_mmhg, heart_rate_bpm, spo2_pct, temperature_f, bmi,
        respiratory_rate, hba1c_pct, glucose_mg_dl, creatinine_mg_dl,
        wbc_10e3_ul, nt_probnp_pg_ml, medication_adherence_pdc, readmission_30d_flag,
        triage_timestamp, admit_timestamp, bed_request_time, bed_assign_time,
        unit_assigned, bed_occupancy_pct, cpt_code, procedure_display,
        or_start, or_end, actual_or_minutes, or_turnover_minutes,
        los_days, discharge_timestamp, safety_incident_flag, incident_type, incident_severity,
        claim_id, payer, npi_billing, drg_weight,
        submitted_charge_usd, allowed_amount_usd, patient_responsibility_usd,
        fraud_upcoding_flag, fraud_duplicate_flag, fraud_unbundling_flag,
        nurse_emp_id, nurse_role, nurse_unit, nurse_tenure_years, nurse_fte,
        surgeon_emp_id, surgeon_specialty, shift_hours, patients_per_nurse_ratio,
        overtime_hours, burnout_exhaustion_mbi, burnout_cynicism_mbi,
        burnout_personal_accomplishment_mbi,  -- ++ ADDED: MBI third subscale
        turnover_risk_index,
        cahps_nurse_communication, cahps_doctor_communication, cahps_responsiveness,
        cahps_pain_management, cahps_discharge_info, cahps_care_transition,
        cahps_cleanliness, cahps_quietness,
        surgical_kit_id, kit_name, kit_unit_cost_usd, kit_current_stock,
        kit_reorder_point, kit_lead_time_days, kit_expiration_date, stockout_risk_flag,
        weekly_procedure_volume, projected_demand_4wk, days_of_supply,
        hedis_hba1c_tested, hedis_hba1c_poor_control, pdsa_cycle_id, himss_emram_stage
    FROM rejects
    WHERE failed_col IS NULL;

    -- Add another table for catching rejected rows.

    -- @@ROWCOUNT captures rows inserted by the statement immediately above.
    -- Rejected count = total staging rows for this batch minus successfully loaded rows.
    -- We cannot re-query the CTE 'rejects' here — CTEs only exist within the
    -- single statement that defines them and are gone after the INSERT completes.
    SET @rows_loaded   = @@ROWCOUNT;
    SET @rows_rejected = (
        SELECT COUNT(*) FROM stg.encounters_raw
        WHERE _load_batch_id = @batch_id
    ) - @rows_loaded;
    SET @duration_ms   = DATEDIFF(MILLISECOND, @start_time, SYSUTCDATETIME());
END;
GO